server:
    port: 8080

spring:
    datasource:
        url: jdbc:oracle:thin:@los-ml.cdcr41rkqhvy.ap-south-1.rds.amazonaws.com:1521/ORCL
        username: SERVOML
        password: Am!t76#20Put$
        driver-class-name: oracle.jdbc.OracleDriver

    jpa:
        datasource-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
            show-sql: true
    h2:
        console:
            enabled: true

